import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {useDispatch, useSelector} from "react-redux";
import { setStatusModalWithPortal, setStatusModalWithoutPortal } from "../store/modal";
import ModalWithPortal from "../components/modalWithPortal";
import ModalWithoutPortal from "../components/modalWithoutPortal";

export const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { statusModalWithPortal, statusModalWithoutPortal } = useSelector(state => state.modal)
  const dispatch = useDispatch()

  // console.log('statusModalWithPortal', statusModalWithPortal, statusModalWithoutPortal)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <button
            className={styles.card}
            onClick={() => dispatch(setStatusModalWithoutPortal(true))}
          >
            <h2 className={inter.className}>
              Popup without portal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </button>

          <button
            className={styles.card}
            onClick={() => dispatch(setStatusModalWithPortal(true))}
          >
            <h2 className={inter.className}>
              Popup with portal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </button>
        </div>
        <ModalWithPortal
            title={'Modal with portal'}
            show={statusModalWithPortal}
            onClose={() => dispatch(setStatusModalWithPortal(false)) }
        >
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci amet commodi deleniti, eius eligendi, hic illum impedit inventore iusto nam necessitatibus neque nulla perferendis placeat qui rem repellendus repudiandae voluptate?
        </ModalWithPortal>
        <ModalWithoutPortal
            show={statusModalWithoutPortal}
            onClose={() => dispatch(setStatusModalWithoutPortal(false)) }
            title={'Modal without portal'}
        >
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci amet commodi deleniti, eius eligendi, hic illum impedit inventore iusto nam necessitatibus neque nulla perferendis placeat qui rem repellendus repudiandae voluptate?
        </ModalWithoutPortal>
      </main>
    </>
  )
}
